# Generated by Django 6.0.3 on 2026-03-18 11:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('education_level', models.CharField(choices=[('None', 'None'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher', 'Higher')], max_length=10)),
                ('mmse_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('moca_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('hypertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('history_of_stroke', models.BooleanField(default=False)),
                ('depression', models.BooleanField(default=False)),
                ('family_history_of_alzheimers', models.BooleanField(default=False)),
                ('smoking_status', models.CharField(choices=[('Never', 'Never'), ('Former', 'Former'), ('Current', 'Current')], max_length=10)),
                ('sleep_hours_per_day', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
