# Generated by Django 6.0.3 on 2026-03-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_percentage', models.FloatField()),
                ('predicted_status', models.CharField(max_length=50)),
                ('eeg_data_json', models.JSONField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_reports', to='patients.patient')),
            ],
        ),
    ]
