# Generated by Django 5.1.15 on 2026-06-05 17:01
#
# Migrates DiagnosisReport.patient from a ForeignKey to a OneToOneField so that
# every assessment has at most one diagnosis report. Before adding the unique
# constraint we drop any duplicate reports left over from the old (non-idempotent)
# create-on-every-call behaviour, keeping the most recent report per patient.

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def dedupe_reports(apps, schema_editor):
    DiagnosisReport = apps.get_model('patients', 'DiagnosisReport')
    seen = set()
    # Newest first; keep the first one seen per patient, delete the rest.
    for report in DiagnosisReport.objects.order_by('patient_id', '-created_at', '-id').iterator():
        if report.patient_id in seen:
            report.delete()
        else:
            seen.add(report.patient_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_new_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='eeg_data_json',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(dedupe_reports, noop),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_report', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='predicted_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('MCI (Mild Cognitive Impairment)', 'MCI (Mild Cognitive Impairment)'), ("AD (Alzheimer's Disease)", "AD (Alzheimer's Disease)")], max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='risk_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
