# Generated by Django 6.0.6 on 2026-06-07 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_diagnosisreport_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreport',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='clinical_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='eeg_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='face_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='fusion_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='modalities_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='speech_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='eeg_data_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='predicted_status',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('MCI (Mild Cognitive Impairment)', 'MCI (Mild Cognitive Impairment)'), ("AD (Alzheimer's Disease)", "AD (Alzheimer's Disease)")], max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='risk_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
